
export const FETCH_START = 'FETCH_START';
export const FETCH_THREADS = 'FETCH_THREADS';
export const FETCH_THREAD = 'FETCH_THREAD';
export const REFETCH = 'REFETCH';

export const NEW_THREAD = 'NEW_THREAD';
export const NEW_PRIVATE_THREAD = 'NEW_PRIVATE_THREAD';
export const FETCH_PRIVATE_THREADS = 'FETCH_PRIVATE_THREADS';
export const FETCH_PRIVATE_THREAD = 'FETCH_PRIVATE_THREAD';

export const REMOVE_THREAD = 'REMOVE_THREAD';

export const NEW_POST = 'NEW_POST';

export const SET_PATH = 'SET_PATH';


